server:
  port: 8333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/how2java?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver